import { chromium } from 'playwright';
import { createServer } from 'vite';
const CHROME='/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
const PORT=5181;
const server=await createServer({server:{port:PORT},logLevel:'warn'}); await server.listen();
const b=await chromium.launch({executablePath:CHROME});
const p=await (await b.newContext({viewport:{width:1100,height:1500},deviceScaleFactor:1})).newPage();
await p.goto(`http://localhost:${PORT}/`,{waitUntil:'networkidle'});
await p.waitForSelector('.topbar');
await p.fill('[data-meta="protokolNr"]','16/2026');
await p.fill('[data-meta="dataKontroli"]','14.05.2026 r.');
await p.fill('[data-meta="adres"]','03-286 Warszawa, ul. Żeromskiego 17');
await p.fill('[data-meta="nazwaObiektu"]','Budynek mieszkalny wielorodzinny z usługami');
await p.fill('#nowa-sekcja-nazwa','Hala garażowa — konstrukcja (ściany, słupy, stropy)');
await p.click('[data-action="dodaj-sekcje"]');
await p.waitForSelector('.sekcja-title');
const sec=await p.getAttribute('[data-sec-card]','data-sec-card');
await p.selectOption(`[data-sec="${sec}"][data-field="ogolnaOcena"]`,'Dostateczny');
await p.click(`[data-action="dodaj-ust"][data-sec="${sec}"]`);
await p.fill(`[data-sec="${sec}"][data-field="text"]`,'Uraz mechaniczny naroża słupa przy stanowisku postojowym nr 26. Rozważyć montaż narożnika osłaniającego.');
await p.locator(`[data-sec="${sec}"][data-field="pilnosc"]`).first().selectOption('4');
await p.click(`[data-action="dodaj-ust"][data-sec="${sec}"]`);
await p.locator(`[data-sec="${sec}"][data-field="text"]`).nth(1).fill('Stropy ze spękaniami — poddane obserwacji za pomocą szkiełek pomiarowych.');
await p.locator(`[data-sec="${sec}"][data-field="pilnosc"]`).nth(1).selectOption('3');
await p.waitForTimeout(300);
await p.screenshot({path:'/tmp/app-ui.png',fullPage:true});
console.log('screenshot saved');
await b.close(); await server.close();
